### ISSUE TITLE
Error Running App

### ISSUE THREAD

**Issue by dsibiski** [hughnguy/trivia-game#1]
Hi @hughnguy,

I'm having a problem running the app from a fresh repo clone, `yarn install` and just opening it up in Expo...please see the below screenshot.

If you can, send over more instructions (if I missed a step) or please commit a bug fix.

Thanks,
Dave

![screenshot 2018-04-11 10 54 41](https://user-images.githubusercontent.com/2922932/38624804-f8fab068-3d76-11e8-8254-3efc2e90bb39.png)

**Comment by hughnguy** [comment]
@dsibiski Hi Dave, I pushed up changes and tried downgrading the expo version. Also i'm using npm for dependency management but I don't think that should make any difference. With the new code can you try in the root directory:

npm install
npm start
press "i" to launch iOS simulator

I also just tested with expo and it seems to work. Let me know if you still run into any issues.

Cheers

**Comment by dsibiski** [comment]
Thanks, it's working now!
